services:
  - type: web
    name: web-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PORT
        value: 10000

  - type: worker
    name: tg-bot
    env: python
    buildCommand: ""
    startCommand: python3 main.py
    plan: free
    envVars:
      - key: API_ID
        value: your_api_id_here
      - key: API_HASH
        value: your_api_hash_here
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: MONGO_URL
        value: your_mongodb_url_here
      - key: LOG_GROUP_ID
        value: your_log_group_id_here
      - key: MINI_APP_URL
        value: https://web-app-name.onrender.com  # replace with actual Render webapp URL
      - key: YT_THUMBNAIL
        value: https://telegra.ph/file/your-default-thumbnail.jpg